export enum SystemRole {
	SUPER_ADMIN = "SUPER_ADMIN",
	PLATFORM_ADMIN = "PLATFORM_ADMIN",
	CITY_ADMIN = "CITY_ADMIN",
	DEPARTMENT_MANAGER = "DEPARTMENT_MANAGER",
	DISPATCHER = "DISPATCHER",
	TECHNICIAN = "TECHNICIAN",
	CITIZEN = "CITIZEN",
}
